name: Application Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PIP_CACHE_DIR: $HOME/.pip
  POETRY_CACHE_DIR: $HOME/.poetry

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install
        
    - name: Print documentation
      run: poetry run publicator --help
    
    - name: Run unit tests
      run: poetry run pytest --verbose
      
